### ISSUE TITLE
How to train?

### ISSUE THREAD

**Issue by hamaadtahir** [BramSW/iccv_2019_few_shot_3d_wallace#1]
With reference to the paper "Few-Shot Generalization for Single-Image 3D Reconstruction via Priors", could you provide some description regarding the training?

**Comment by hamaadtahir** [comment]
With reference to the paper "Few-Shot Generalization for Single-Image 3D Reconstruction via Priors", could you provide some description regarding the training?

**Comment by BramSW** [comment]
Hi! Thanks for bringing the lack of documentation to my attention; I apologize for that.  I added in a README which describes how to download the data and points out the main training script. Let me know if you have any more questions?

**Comment by hamaadtahir** [comment]
Thankyou
